### ISSUE TITLE
Localized model not showing unless I set the locale again in the controller action

### ISSUE THREAD

**Issue by quarente** [nevadskiy/laravel-translatable#32]
When I change the locale with a package (mcamara/laravel-localization) the translated models are not showing. 

`dd(app()->getLocale()) `
outputs 'en'
Model is shown in the default (nl) language

If I add 
`app()->setLocale(app()->getLocale()) `
the correct language is shown (en)

**Comment by nevadskiy** [comment]
@quarente do you have set 'nl' as a fallback locale?

**Comment by xalaida** [comment]
Should be fine after #38
