### ISSUE TITLE
Does this work with Laravel 8.x  and the Lumen equivalent

### ISSUE THREAD

**Issue by patforg** [nevadskiy/laravel-translatable#36]
This package looks awesome, just wondering does this work with Laravel 8.x?

Does it work with Lumen took?

**Comment by xalaida** [comment]
@patforg thank you.
I'm working on new version in a dev branch that will support Laravel 8 (no Lumen but Laravel Octane).
I will try to release it in few days.

**Comment by patforg** [comment]
That is awesome @nevadskiy.  Let me know once it's pushed, we can see if we can get it working on Lumen.

**Comment by nevadskiy** [comment]
@patforg I have done a major pre-release that are very different from the previous version.
