### ISSUE TITLE
Supportig a hidden model functionality

### ISSUE THREAD

**Issue by mcmc4519** [nevadskiy/laravel-translatable#46]
Dear @nevadskiy 

Thank you for your package!

Amazing job!

I use it in my project, and it very useful for me!

I have an issue about supporting a hidden model option

My example is:

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Nevadskiy\Translatable\Strategies\ExtraTableExtended\HasTranslations;

class OrderType extends Model
{

   protected $translatable = [
		'name',
		'description',
	];

  protected $hidden = ['description'];
}
?>
```

A almost of times I don't need to have a **description** field in the json response.
But sometime I need it. 

The first question is:
Can I change dynamically a $translatable attribute?

The second question is: is your package support a $hidden  models attribute?

**Comment by xalaida** [comment]
Thanks buddy, @mcmc4519.

1. You actually do not need to dynamically set $translatable attributes.
2. My package should work fine with $hidden attributes, however, I recommend you to do it in another way.

Take a look at Json Resources: https://laravel.com/docs/eloquent-resources.

**Comment by mcmc4519** [comment]
@nevadskiy  thank you a lot, man! 

I solved my task by json resource!
